import React from 'react'

export const listaDePaises=[
    <option key='1' value="África do Sul">África do Sul</option>,
    <option key='2' value="Albânia">Albânia</option>,
    <option key='3' value="Alemanha">Alemanha</option>,
    <option key='4' value="Andorra">Andorra</option>,
    <option key='5' value="Angola">Angola</option>,
    <option key='6' value="Anguilla">Anguilla</option>,
    <option key='7' value="Antigua">Antigua</option>,
    <option key='8' value="Arábia Saudita">Arábia Saudita</option>,
    <option key='9' value="Argentina">Argentina</option>,
    <option key='10' value="Armênia">Armênia</option>,
    <option key='11' value="Aruba">Aruba</option>,
    <option key='12' value="Austrália">Austrália</option>,
    <option key='13' value="Áustria">Áustria</option>,
    <option key='14' value="Azerbaijão">Azerbaijão</option>,
    <option key='15' value="Bahamas">Bahamas</option>,
    <option key='16' value="Bahrein">Bahrein</option>,
    <option key='17' value="Bangladesh">Bangladesh</option>,
    <option key='18' value="Barbados">Barbados</option>,
    <option key='19' value="Bélgica">Bélgica</option>,
    <option key='20' value="Benin">Benin</option>,
    <option key='21' value="Bermudas">Bermudas</option>,
    <option key='22' value="Botsuana">Botsuana</option>,
    <option key='24' value="Brunei">Brunei</option>,
    <option key='25' value="Bulgária">Bulgária</option>,
    <option key='26' value="Burkina Fasso">Burkina Fasso</option>,
    <option key='27' value="botão">botão</option>,
    <option key='28' value="Cabo Verde">Cabo Verde</option>,
    <option key='29' value="Camarões">Camarões</option>,
    <option key='30' value="Camboja">Camboja</option>,
    <option key='31' value="Canadá">Canadá</option>,
    <option key='32' value="Cazaquistão">Cazaquistão</option>,
    <option key='33' value="Chade">Chade</option>,
    <option key='34' value="Chile">Chile</option>,
    <option key='35' value="China">China</option>,
    <option key='36' value="Cidade do Vaticano">Cidade do Vaticano</option>,
    <option key='37' value="Colômbia">Colômbia</option>,
    <option key='38' value="Congo">Congo</option>,
    <option key='39' value="Coréia do Sul">Coréia do Sul</option>,
    <option key='40' value="Costa do Marfim">Costa do Marfim</option>,
    <option key='41' value="Costa Rica">Costa Rica</option>,
    <option key='42' value="Croácia">Croácia</option>,
    <option key='43' value="Dinamarca">Dinamarca</option>,
    <option key='44' value="Djibuti">Djibuti</option>,
    <option key='45' value="Dominica">Dominica</option>,
    <option key='46' value="EUA">EUA</option>,
    <option key='47' value="Egito">Egito</option>,
    <option key='48' value="El Salvador">El Salvador</option>,
    <option key='49' value="Emirados Árabes">Emirados Árabes</option>,
    <option key='50' value="Equador">Equador</option>,
    <option key='51' value="Eritréia">Eritréia</option>,
    <option key='52' value="Escócia">Escócia</option>,
    <option key='53' value="Eslováquia">Eslováquia</option>,
    <option key='54' value="Eslovênia">Eslovênia</option>,
    <option key='55' value="Espanha">Espanha</option>,
    <option key='56' value="Estônia">Estônia</option>,
    <option key='57' value="Etiópia">Etiópia</option>,
    <option key='58' value="Fiji">Fiji</option>,
    <option key='59' value="Filipinas">Filipinas</option>,
    <option key='60' value="Finlândia">Finlândia</option>,
    <option key='61' value="França">França</option>,
    <option key='62' value="Gabão">Gabão</option>,
    <option key='63' value="Gâmbia">Gâmbia</option>,
    <option key='64' value="Gana">Gana</option>,
    <option key='65' value="Geórgia">Geórgia</option>,
    <option key='66' value="Gibraltar">Gibraltar</option>,
    <option key='67' value="Granada">Granada</option>,
    <option key='68' value="Grécia">Grécia</option>,
    <option key='69' value="Guadalupe">Guadalupe</option>,
    <option key='70' value="Guam">Guam</option>,
    <option key='71' value="Guatemala">Guatemala</option>,
    <option key='72' value="Guiana">Guiana</option>,
    <option key='73' value="Guiana Francesa">Guiana Francesa</option>,
    <option key='74' value="Guiné-bissau">Guiné-bissau</option>,
    <option key='75' value="Haiti">Haiti</option>,
    <option key='76' value="Holanda">Holanda</option>,
    <option key='77' value="Honduras">Honduras</option>,
    <option key='78' value="Hong Kong">Hong Kong</option>,
    <option key='79' value="Hungria">Hungria</option>,
    <option key='80' value="Iêmen">Iêmen</option>,
    <option key='81' value="Ilhas Cayman">Ilhas Cayman</option>,
    <option key='82' value="Ilhas Cook">Ilhas Cook</option>,
    <option key='83' value="Ilhas Curaçao">Ilhas Curaçao</option>,
    <option key='84' value="Ilhas Marshall">Ilhas Marshall</option>,
    <option key='85' value="Ilhas Turks & Caicos">Ilhas Turks & Caicos</option>,
    <option key='86' value="Ilhas Virgens (brit.)">Ilhas Virgens (brit.)</option>,
    <option key='87' value="Ilhas Virgens(amer.)">Ilhas Virgens(amer.)</option>,
    <option key='88' value="Ilhas Wallis e Futuna">Ilhas Wallis e Futuna</option>,
    <option key='89' value="Índia">Índia</option>,
    <option key='90' value="Indonésia">Indonésia</option>,
    <option key='91' value="Inglaterra">Inglaterra</option>,
    <option key='92' value="Irlanda">Irlanda</option>,
    <option key='93' value="Islândia">Islândia</option>,
    <option key='94' value="Israel">Israel</option>,
    <option key='95' value="Itália">Itália</option>,
    <option key='96' value="Jamaica">Jamaica</option>,
    <option key='97' value="Japão">Japão</option>,
    <option key='98' value="Jordânia">Jordânia</option>,
    <option key='99' value="Kuwait">Kuwait</option>,
    <option key='100' value="Latvia">Latvia</option>,
    <option key='101' value="Líbano">Líbano</option>,
    <option key='102' value="Liechtenstein">Liechtenstein</option>,
    <option key='103' value="Lituânia">Lituânia</option>,
    <option key='104' value="Luxemburgo">Luxemburgo</option>,
    <option key='105' value="Macau">Macau</option>,
    <option key='106' value="Macedônia">Macedônia</option>,
    <option key='107' value="Madagascar">Madagascar</option>,
    <option key='108' value="Malásia">Malásia</option>,
    <option key='109' value="Malaui">Malaui</option>,
    <option key='110' value="Mali">Mali</option>,
    <option key='111' value="Malta">Malta</option>,
    <option key='112' value="Marrocos">Marrocos</option>,
    <option key='113' value="Martinica">Martinica</option>,
    <option key='114' value="Mauritânia">Mauritânia</option>,
    <option key='115' value="Mauritius">Mauritius</option>,
    <option key='116' value="México">México</option>,
    <option key='117' value="Moldova">Moldova</option>,
    <option key='118' value="Mônaco">Mônaco</option>,
    <option key='119' value="Montserrat">Montserrat</option>,
    <option key='120' value="Nepal">Nepal</option>,
    <option key='121' value="Nicarágua">Nicarágua</option>,
    <option key='122' value="Niger">Niger</option>,
    <option key='123' value="Nigéria">Nigéria</option>,
    <option key='124' value="Noruega">Noruega</option>,
    <option key='125' value="Nova Caledônia">Nova Caledônia</option>,
    <option key='126' value="Nova Zelândia">Nova Zelândia</option>,
    <option key='127' value="Omã">Omã</option>,
    <option key='128' value="Palau">Palau</option>,
    <option key='129' value="Panamá">Panamá</option>,
    <option key='130' value="Papua-nova Guiné">Papua-nova Guiné</option>,
    <option key='131' value="Paquistão">Paquistão</option>,
    <option key='132' value="Peru">Peru</option>,
    <option key='133' value="Polinésia Francesa">Polinésia Francesa</option>,
    <option key='134' value="Polônia">Polônia</option>,
    <option key='135' value="Porto Rico">Porto Rico</option>,
    <option key='136' value="Portugal">Portugal</option>,
    <option key='137' value="Qatar">Qatar</option>,
    <option key='138' value="Quênia">Quênia</option>,
    <option key='139' value="Rep. Dominicana">Rep. Dominicana</option>,
    <option key='140' value="Rep. Tcheca">Rep. Tcheca</option>,
    <option key='141' value="Reunion">Reunion</option>,
    <option key='142' value="Romênia">Romênia</option>,
    <option key='143' value="Ruanda">Ruanda</option>,
    <option key='144' value="Rússia">Rússia</option>,
    <option key='145' value="Saipan">Saipan</option>,
    <option key='146' value="Samoa Americana">Samoa Americana</option>,
    <option key='147' value="Senegal">Senegal</option>,
    <option key='148' value="Serra Leone">Serra Leone</option>,
    <option key='149' value="Seychelles">Seychelles</option>,
    <option key='150' value="Singapura">Singapura</option>,
    <option key='151' value="Síria">Síria</option>,
    <option key='152' value="Sri Lanka">Sri Lanka</option>,
    <option key='153' value="St. Kitts & Nevis">St. Kitts & Nevis</option>,
    <option key='154' value="St. Lúcia">St. Lúcia</option>,
    <option key='155' value="St. Vincent">St. Vincent</option>,
    <option key='156' value="Sudão">Sudão</option>,
    <option key='157' value="Suécia">Suécia</option>,
    <option key='158' value="Suiça">Suiça</option>,
    <option key='159' value="Suriname">Suriname</option>,
    <option key='160' value="Tailândia">Tailândia</option>,
    <option key='161' value="Taiwan">Taiwan</option>,
    <option key='162' value="Tanzânia">Tanzânia</option>,
    <option key='163' value="Togo">Togo</option>,
    <option key='164' value="Trinidad & Tobago">Trinidad & Tobago</option>,
    <option key='165' value="Tunísia">Tunísia</option>,
    <option key='166' value="Turquia">Turquia</option>,
    <option key='167' value="Ucrânia">Ucrânia</option>,
    <option key='168' value="Uganda">Uganda</option>,
    <option key='169' value="Uruguai">Uruguai</option>,
    <option key='170' value="Venezuela">Venezuela</option>,
    <option key='171' value="Vietnã">Vietnã</option>,
    <option key='172' value="Zaire">Zaire</option>,
    <option key='173' value="Zâmbia">Zâmbia</option>,
    <option key='174' value="Zimbábue">Zimbábue</option>
]